### ISSUE TITLE
Agoric dapp card store

### ISSUE THREAD

**Issue by danishyasin33** [robor-systems/agoric-card-store#1]
## Description
Modify Agoric’s dapp-card-store to allow users to list their own cards for sale. Make the following modifications to the UI:

- Add “My Cards” page which displays the cards owned by the user
- Add “Marketplace” page which shows secondary sales listings
- Current dapp page which sells cards to user directly becomes “Primary Sales”

User should be able to list their card for sale. User flow:

1. User navigates to “My Cards” page
2. User selects a card to list for sale
3. User chooses the sale mechanism (currently only one - Fixed price sale)
4. Choose price for listing in RUN
5. Optional for user: Choose end date & time for the listing
6. User confirms choice and creates listing
7. User navigates to “Marketplace” page and can see all marketplace listings and filter to his/her own listing(s)

## Context
Agoric has an example dapp which allows users to purchase Baseball card NFTs directly from the application for a fixed price. The dapp instantiates a separate contract to sell these items and includes a basic front end.

For this project, we’d like you to extend the Dapp card store to allow holders of baseball cards to offer theirs for sale at a fixed price.

## Current Implementation: 
https://github.com/Agoric/dapp-card-store

**Comment by aamnasarosh** [comment]
Wireframes progress: https://xd.adobe.com/view/febcdf70-7d97-415b-ab34-bae649ac4104-abef/
(These are just the wireframes not final UI)

**Comment by aamnasarosh** [comment]
Agoric card UI progress: https://xd.adobe.com/view/ed78c606-cba3-440e-ad81-634fbdd46ce9-b82b/

**Comment by aamnasarosh** [comment]
Agoric baseball card: https://xd.adobe.com/view/ed78c606-cba3-440e-ad81-634fbdd46ce9-b82b/
another variation (only blurred background for fullscreen images): https://xd.adobe.com/view/40cc39a4-cfd7-46cd-bcba-fcfac7596d85-159f/

- for 'on sale' products on My Cards, hover over the blue tag icons to see the tool tip
- full screen image view added
- profile and settings removed from top-right
- agoric wallet status added
- sale ending time removed from primary marketplace

**Comment by aamnasarosh** [comment]
Time spent in sprint 4: 12 hrs

**Comment by aamnasarosh** [comment]
Dev link

> Agoric baseball card: https://xd.adobe.com/view/ed78c606-cba3-440e-ad81-634fbdd46ce9-b82b/ another variation (only blurred background for fullscreen images): https://xd.adobe.com/view/40cc39a4-cfd7-46cd-bcba-fcfac7596d85-159f/
> 
> * for 'on sale' products on My Cards, hover over the blue tag icons to see the tooltip
> * full screen image view added
> * profile and settings removed from top-right
> * agoric wallet status added
> * sale ending time removed from primary marketplace

Dev Link: https://xd.adobe.com/view/d825c6e4-887c-4432-9c98-5fce91a25cb2-8d76/

**Comment by danishyasin33** [comment]
@aamnasarosh duplicate of #2, all progress tracked in #2. Closing this ticket.
